# Stack arrays a and b vertically
Input:
* a = np.arange(10).reshape(2,-1)
* b = np.repeat(1, 10).reshape(2,-1)

In [1]:
import numpy as np

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [6]:
a, b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [8]:
# Method 1
stack_v = np.vstack([a, b])
stack_v

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
# Methos 2
stack_v = np.concatenate([a, b], axis=0)
stack_v

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
# Method 3
stack_v = np.r_[a, b]
stack_v

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])