# Stack the arrays a and b horizontally.
input:
* a = np.arange(10).reshape(2,-1)
* b = np.repeat(1, 10).reshape(2,-1)

In [1]:
import numpy as np

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [2]:
a, b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [4]:
# Method 1
stack_h = np.hstack([a,b])
stack_h

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [6]:
# Method 2
stack_h = np.concatenate([a, b], axis=1)
stack_h

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [7]:
# Method 3
stack_h = np.c_[a,b]
stack_h

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])